services:
  nginx:
    ports:
      - "443:443"
    volumes:
      - ./nginx/https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf/live/${SSL_DOMAIN}:/etc/nginx/certs/live:ro
      - ./certbot/conf/archive/${SSL_DOMAIN}:/etc/nginx/certs/archive:ro

  certbot:
    image: certbot/certbot:latest
    profiles: ["certbot"]
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
