services:
  db:
    image: mysql:8.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    # ports:
    #   - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30

  web:
    build: .
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - static_data:/app/staticfiles
      - media_data:/app/media
    command:
      - /bin/sh
      - -c
      - |
        tr -d '\r' < /app/entrypoint.sh > /tmp/entrypoint.sh
        chmod +x /tmp/entrypoint.sh
        exec /tmp/entrypoint.sh
    restart: unless-stopped
    environment:
      TZ: Asia/Yekaterinburg
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:-}
      TELEGRAM_NOTIFICATIONS: ${TELEGRAM_NOTIFICATIONS:-0}

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "${NGINX_HTTP_PORT:-8000}:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro`
      - ./certbot/www:/var/www/certbot:ro
      - ./certs/woom-fit.ru:/etc/nginx/certs
      - static_data:/app/staticfiles:ro
      - media_data:/app/media:ro
    restart: unless-stopped


volumes:
  mysql_data:
  static_data:
  media_data:
